import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BookOpen, Bookmark, Check, ChevronLeft, Clock3, Code2, Command, Moon, Play, RotateCcw, Search, Shuffle, Sun, Target, Trophy, X } from 'lucide-react';
import { questions, subjects, type Question, type Difficulty } from './data/questions';
import './styles.css';

type Store = { bookmarks: number[]; mastered: number[]; attempts: number; score: number; lastStudy?: string; streak: number; theme: 'light'|'dark' };
const defaultStore: Store = { bookmarks: [], mastered: [], attempts: 0, score: 0, streak: 0, theme: 'light' };
const readStore = (): Store => { try { return { ...defaultStore, ...JSON.parse(localStorage.getItem('prep-store') || '{}') }; } catch { return defaultStore; } };
const today = () => new Date().toISOString().slice(0, 10);
const codeFor = (q: Question) => q.subject === 'DBMS' ? `SELECT department, COUNT(*) AS hires\nFROM employees\nGROUP BY department\nHAVING COUNT(*) > 3;` : q.subject === 'Java & OOP' ? `// ${q.title}\nclass InterviewExample {\n  public static void main(String[] args) {\n    System.out.println("Explain the trade-off clearly");\n  }\n}` : `// ${q.title}\n// State the invariant, then choose the simplest correct approach.\npublic void solve() {\n  // analyse time and space before coding\n}`;

function App() {
  const [store, setStore] = useState<Store>(readStore);
  const [page, setPage] = useState<'dashboard'|'library'|'detail'|'mock'|'revision'>('dashboard');
  const [selected, setSelected] = useState<Question>(questions[0]);
  const [query, setQuery] = useState(''); const [subject, setSubject] = useState('All'); const [difficulty, setDifficulty] = useState('All'); const [frequency, setFrequency] = useState('All');
  const [mock, setMock] = useState<Question[]>([]); const [mockIndex, setMockIndex] = useState(0); const [mockAnswers, setMockAnswers] = useState<Record<number, boolean>>({}); const [seconds, setSeconds] = useState(600);
  useEffect(() => { localStorage.setItem('prep-store', JSON.stringify(store)); document.documentElement.dataset.theme = store.theme; }, [store]);
  useEffect(() => { if (page !== 'mock' || !mock.length || seconds <= 0) return; const id = setInterval(() => setSeconds(n => n - 1), 1000); return () => clearInterval(id); }, [page, mock.length, seconds]);
  const study = () => setStore(s => { const gap = s.lastStudy ? Math.round((Date.parse(today()) - Date.parse(s.lastStudy)) / 86400000) : 0; return { ...s, lastStudy: today(), streak: s.lastStudy === today() ? s.streak : gap === 1 ? s.streak + 1 : 1 }; });
  const toggle = (key: 'bookmarks'|'mastered', id: number) => { study(); setStore(s => ({ ...s, [key]: s[key].includes(id) ? s[key].filter(x => x !== id) : [...s[key], id] })); };
  const open = (q: Question) => { study(); setSelected(q); setPage('detail'); window.scrollTo(0,0); };
  const filtered = useMemo(() => questions.filter(q => (!query || `${q.title} ${q.answer} ${q.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())) && (subject === 'All'||q.subject===subject) && (difficulty==='All'||q.difficulty===difficulty) && (frequency==='All'||q.frequency===frequency)), [query, subject,difficulty,frequency]);
  const startMock = () => { study(); setMock([...questions].sort(() => Math.random()-.5).slice(0,10)); setMockIndex(0); setMockAnswers({}); setSeconds(600); setPage('mock'); };
  const submitMock = () => { const score = Object.values(mockAnswers).filter(Boolean).length; setStore(s => ({...s, attempts:s.attempts+1, score: Math.max(s.score, score)})); setSeconds(0); };
  const nav = (p: typeof page) => { setPage(p); window.scrollTo(0,0); };
  return <div className="app">
    <header><button className="brand" onClick={() => nav('dashboard')}><span className="brand-mark">&lt;/&gt;</span><span>Prep<span>Forge</span></span></button><nav><button className={page==='dashboard'?'active':''} onClick={()=>nav('dashboard')}>Dashboard</button><button className={page==='library'||page==='detail'?'active':''} onClick={()=>nav('library')}>Question library</button><button className={page==='revision'?'active':''} onClick={()=>nav('revision')}>Quick revision</button></nav><button className="icon-button" aria-label="Toggle theme" onClick={()=>setStore(s=>({...s,theme:s.theme==='light'?'dark':'light'}))}>{store.theme==='light'?<Moon size={19}/>:<Sun size={19}/>}</button></header>
    <nav className="mobile-nav" aria-label="Mobile navigation"><button className={page==='dashboard'?'active':''} onClick={()=>nav('dashboard')}>Dashboard</button><button className={page==='library'||page==='detail'?'active':''} onClick={()=>nav('library')}>Library</button><button className={page==='revision'?'active':''} onClick={()=>nav('revision')}>Revision</button><button className={page==='mock'?'active':''} onClick={startMock}>Mock</button></nav>
    {page==='dashboard' && <Dashboard store={store} onLibrary={()=>nav('library')} onMock={startMock} onRevision={()=>nav('revision')} onOpen={open}/>} 
    {page==='library' && <Library filtered={filtered} query={query} setQuery={setQuery} subject={subject} setSubject={setSubject} difficulty={difficulty} setDifficulty={setDifficulty} frequency={frequency} setFrequency={setFrequency} store={store} toggle={toggle} open={open}/>} 
    {page==='detail' && <Detail q={selected} store={store} toggle={toggle} back={()=>nav('library')} open={open}/>} 
    {page==='revision' && <Revision store={store} open={open} onMock={startMock}/>} 
    {page==='mock' && <Mock mock={mock} index={mockIndex} answers={mockAnswers} seconds={seconds} setIndex={setMockIndex} setAnswers={setMockAnswers} quit={()=>nav('dashboard')} submit={submitMock} open={open}/>} 
  </div>;
}

function Dashboard({store,onLibrary,onMock,onRevision,onOpen}:{store:Store;onLibrary:()=>void;onMock:()=>void;onRevision:()=>void;onOpen:(q:Question)=>void}) { const pct=Math.round(store.mastered.length/questions.length*100); const picks=questions.filter(q=>!store.mastered.includes(q.id)).slice(0,3); return <main className="dashboard"><section className="hero"><div><p className="eyebrow">YOUR INTERVIEW COMMAND CENTER</p><h1>Build calm confidence,<br/><i>one concept at a time.</i></h1><p className="sub">A practical CSE interview curriculum with crisp answers, real code, and deliberate practice.</p><div className="row"><button className="primary" onClick={onLibrary}>Explore questions <ChevronLeft className="flip" size={18}/></button><button className="secondary" onClick={onMock}><Play size={17}/> Start mock interview</button></div></div><div className="hero-card"><span className="orb"/><Trophy size={28}/><strong>{store.streak} day streak</strong><small>Keep your momentum alive today.</small><div className="progress"><span style={{width:`${Math.max(pct,3)}%`}}/></div><small>{store.mastered.length} of {questions.length} concepts mastered</small></div></section><section className="stat-grid"><Stat label="Mastered" value={`${pct}%`} icon={<Check/>}/><Stat label="Bookmarks" value={store.bookmarks.length} icon={<Bookmark/>}/><Stat label="Mocks completed" value={store.attempts} icon={<Target/>}/><Stat label="Best mock score" value={`${store.score}/10`} icon={<Trophy/>}/></section><section className="section-head"><div><p className="eyebrow">PICK UP WHERE YOU LEFT OFF</p><h2>Recommended for you</h2></div><button className="text-button" onClick={onLibrary}>See all questions →</button></section><div className="cards">{picks.map(q=><QuestionCard key={q.id} q={q} store={store} toggle={()=>{}} open={onOpen}/>)}</div><section className="practice-banner"><div><span className="round-icon"><Shuffle/></span><div><h2>Need a fast refresher?</h2><p>Review compact, interview-ready explanations across every core subject.</p></div></div><button className="secondary" onClick={onRevision}>Enter revision mode →</button></section></main> }
const Stat=({label,value,icon}:{label:string;value:string|number;icon:React.ReactNode})=><div className="stat"><span>{icon}</span><strong>{value}</strong><small>{label}</small></div>;

function Library(p:any){return <main className="library"><section className="library-top"><p className="eyebrow">QUESTION LIBRARY · {questions.length} CURATED CONCEPTS</p><h1>Learn the answer.<br/><i>Own the conversation.</i></h1><p>Filter by the questions that actually show up in technical interviews.</p></section><div className="searchbar"><Search size={20}/><input autoFocus placeholder="Search concepts, keywords, or technologies..." value={p.query} onChange={e=>p.setQuery(e.target.value)}/><kbd><Command size={12}/> K</kbd></div><div className="filters"><Filter label="Subject" value={p.subject} values={['All',...subjects]} set={p.setSubject}/><Filter label="Difficulty" value={p.difficulty} values={['All','Easy','Medium','Hard']} set={p.setDifficulty}/><Filter label="Frequency" value={p.frequency} values={['All','Very High','High','Medium']} set={p.setFrequency}/><span className="result-count">{p.filtered.length} questions</span></div><div className="question-grid">{p.filtered.map((q:Question)=><QuestionCard key={q.id} q={q} {...p}/>)}</div>{!p.filtered.length&&<div className="empty"><Search size={30}/><h3>No matching questions</h3><p>Try clearing a filter or using a broader search.</p></div>}</main>}
function Filter({label,value,values,set}:{label:string;value:string;values:string[];set:(v:string)=>void}){return <label className="filter"><span>{label}</span><select value={value} onChange={e=>set(e.target.value)}>{values.map(v=><option key={v}>{v}</option>)}</select></label>}
function QuestionCard({q,store,toggle,open}:{q:Question;store:Store;toggle:(k:'bookmarks'|'mastered',id:number)=>void;open:(q:Question)=>void}){const saved=store.bookmarks.includes(q.id), done=store.mastered.includes(q.id);return <article className="q-card"><div className="card-top"><span className={`pill ${q.difficulty.toLowerCase()}`}>{q.difficulty}</span><span className="freq">{q.frequency}</span><button aria-label="Bookmark" className={saved?'saved mini-icon':'mini-icon'} onClick={()=>toggle('bookmarks',q.id)}><Bookmark size={17} fill={saved?'currentColor':'none'}/></button></div><small className="subject-label">{q.subject} · {q.category}</small><h3>{q.title}</h3><p>{q.answer}</p><div className="card-foot"><span className="tags">{q.tags.slice(0,2).map(t=><em key={t}>{t}</em>)}</span><button className="read" onClick={()=>open(q)}>Study <ChevronLeft className="flip" size={16}/></button></div>{done&&<span className="mastered"><Check size={13}/> Mastered</span>}</article>}

function Detail({q,store,toggle,back,open}:{q:Question;store:Store;toggle:(k:'bookmarks'|'mastered',id:number)=>void;back:()=>void;open:(q:Question)=>void}){const saved=store.bookmarks.includes(q.id),done=store.mastered.includes(q.id);const related=questions.filter(x=>x.subject===q.subject&&x.id!==q.id).slice(0,3);return <main className="detail"><button className="back" onClick={back}>← Back to library</button><div className="detail-layout"><article><div className="detail-meta"><span className={`pill ${q.difficulty.toLowerCase()}`}>{q.difficulty}</span><span>{q.subject} · {q.category}</span><span>Asked {q.frequency.toLowerCase()}</span></div><h1>{q.title}</h1><div className="answer"><h3>The interview answer</h3><p>{q.answer}</p></div><section><h2>How to explain it</h2><p>{q.explanation}</p></section>{q.diagram&&<section><h2>Mental model</h2><div className="diagram"><div>{q.diagram.split(' → ').map((n,i)=><React.Fragment key={n}><span>{n}</span>{i<q.diagram!.split(' → ').length-1&&<b>→</b>}</React.Fragment>)}</div></div></section>}<section><h2>Example</h2><p>{q.example}</p></section><section><h2>Code example</h2><pre><code>{codeFor(q)}</code></pre></section><section className="tip"><strong>Interview tip</strong><p>{q.tip}</p></section><section><h2>Likely follow-up</h2><p className="follow">“{q.followUp}”</p></section></article><aside><button className={done?'master-button complete':'master-button'} onClick={()=>toggle('mastered',q.id)}>{done?<><Check/> Mastered</>:<><Target/> Mark as mastered</>}</button><button className="save-button" onClick={()=>toggle('bookmarks',q.id)}><Bookmark size={18} fill={saved?'currentColor':'none'}/>{saved?'Saved to bookmarks':'Bookmark question'}</button><div className="side-card"><small>UP NEXT IN {q.subject.toUpperCase()}</small>{related.map(x=><button key={x.id} onClick={()=>open(x)}>{x.title}<ChevronLeft className="flip" size={15}/></button>)}</div></aside></div></main>}
function Revision({store,open,onMock}:{store:Store;open:(q:Question)=>void;onMock:()=>void}){const weak=questions.filter(q=>!store.mastered.includes(q.id));return <main className="library revision"><section className="library-top"><p className="eyebrow">HIGH-VELOCITY REVIEW</p><h1>Quick revision <i>mode.</i></h1><p>Your remaining topics, distilled into sharp talking points. Aim to explain each one aloud before opening it.</p></section><div className="revision-actions"><span><RotateCcw size={18}/> {weak.length} concepts to strengthen</span><button className="primary" onClick={onMock}>Test yourself with a mock</button></div><div className="flash-grid">{weak.map(q=><button className="flash" key={q.id} onClick={()=>open(q)}><span>{q.subject}</span><strong>{q.title}</strong><p>{q.answer}</p><small>Open answer →</small></button>)}</div></main>}
function Mock({mock,index,answers,seconds,setIndex,setAnswers,quit,submit,open}:any){if(!mock.length)return null;const done=seconds<=0, q=mock[index], score=Object.values(answers).filter(Boolean).length;const time=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;return <main className="mock"><div className="mock-top"><button className="back" onClick={quit}>← Exit mock</button><span><Clock3 size={18}/> {time}</span></div>{done?<div className="result"><Trophy size={48}/><p className="eyebrow">MOCK INTERVIEW COMPLETE</p><h1>{score} / 10</h1><p>Score yourself honestly: “yes” means you could explain the concept, trade-offs, and a relevant example without notes.</p><button className="primary" onClick={quit}>Return to dashboard</button></div>:<section className="mock-card"><div className="mock-progress"><span>Question {index+1} of 10</span><div className="progress"><span style={{width:`${(index+1)*10}%`}}/></div></div><p className="eyebrow">{q.subject} · {q.difficulty}</p><h1>{q.title}</h1><p>Take a moment to answer aloud. Then score your own explanation.</p><div className="mock-actions"><button className={answers[q.id]===false?'selected no':'score no'} onClick={()=>setAnswers({...answers,[q.id]:false})}><X/> Need review</button><button className={answers[q.id]===true?'selected yes':'score yes'} onClick={()=>setAnswers({...answers,[q.id]:true})}><Check/> I nailed it</button></div><details><summary>Reveal the answer</summary><p>{q.answer}</p><button onClick={()=>open(q)}>Read full explanation</button></details><div className="next-row"><button className="secondary" disabled={index===0} onClick={()=>setIndex(index-1)}>Previous</button>{index===9?<button className="primary" onClick={submit}>Finish & score</button>:<button className="primary" onClick={()=>setIndex(index+1)}>Next question →</button>}</div></section>}</main>}
createRoot(document.getElementById('root')!).render(<App/>);
